export interface EmojiItem {
  char: string;
  name: string;
  category: 'smileys' | 'gestures' | 'symbols' | 'objects' | 'nature';
}

export interface EmojiCategoryTab {
  id: 'all' | 'smileys' | 'gestures' | 'symbols' | 'objects' | 'nature';
  label: string;
  icon: string;
}

export const EMOJI_CATEGORY_TABS: EmojiCategoryTab[] = [
  { id: 'all', label: 'All', icon: '✨' },
  { id: 'smileys', label: 'Faces', icon: '😀' },
  { id: 'gestures', label: 'Hands', icon: '👍' },
  { id: 'symbols', label: 'Symbols', icon: '❤️' },
  { id: 'objects', label: 'Items', icon: '📦' },
  { id: 'nature', label: 'Food & Life', icon: '☕' },
];

export const FULL_EMOJI_LIST: EmojiItem[] = [
  // --- Smileys & Emotions ---
  { char: '😀', name: 'grinning face happy smile', category: 'smileys' },
  { char: '😃', name: 'smiley happy joy laugh', category: 'smileys' },
  { char: '😄', name: 'smile cheerful teeth', category: 'smileys' },
  { char: '😁', name: 'beam grin teeth proud', category: 'smileys' },
  { char: '😆', name: 'laughing lol haha closed eyes', category: 'smileys' },
  { char: '😅', name: 'sweat smile nervous relief', category: 'smileys' },
  { char: '🤣', name: 'rofl rolling on floor laughing hilarious', category: 'smileys' },
  { char: '😂', name: 'joy tears laughter funny crying', category: 'smileys' },
  { char: '🙂', name: 'slightly smiling okay positive', category: 'smileys' },
  { char: '🙃', name: 'upside down sarcasm silly ironical', category: 'smileys' },
  { char: '😉', name: 'wink flirt playful joke', category: 'smileys' },
  { char: '😊', name: 'blush pleased warm shy', category: 'smileys' },
  { char: '😇', name: 'innocent angel halo holy', category: 'smileys' },
  { char: '🥰', name: 'in love hearts affectionate adore', category: 'smileys' },
  { char: '😍', name: 'heart eyes love enamored infatuated', category: 'smileys' },
  { char: '🤩', name: 'star struck excited amazed', category: 'smileys' },
  { char: '😘', name: 'kiss blow kiss love flirt', category: 'smileys' },
  { char: '😗', name: 'kissing whistling', category: 'smileys' },
  { char: '😋', name: 'delicious yum food tongue hungry', category: 'smileys' },
  { char: '😛', name: 'tongue playful cheeky', category: 'smileys' },
  { char: '😜', name: 'winking tongue crazy party wacky', category: 'smileys' },
  { char: '🤪', name: 'zany silly crazy wild goofy', category: 'smileys' },
  { char: '😝', name: 'squinting tongue gross joke', category: 'smileys' },
  { char: '🤑', name: 'money face rich cash dollars profit', category: 'smileys' },
  { char: '🤗', name: 'hugging warm open hands embrace', category: 'smileys' },
  { char: '🤭', name: 'giggle hand over mouth oops secret', category: 'smileys' },
  { char: '🤫', name: 'shushing quiet silent hush secret', category: 'smileys' },
  { char: '🤔', name: 'thinking consider hmm ponder wonder', category: 'smileys' },
  { char: '🤐', name: 'zipper mouth secret confidential sealed', category: 'smileys' },
  { char: '🤨', name: 'raised eyebrow skeptic suspicious doubt', category: 'smileys' },
  { char: '😐', name: 'neutral blank deadpan straight', category: 'smileys' },
  { char: '😑', name: 'expressionless poker face unimpressed', category: 'smileys' },
  { char: '😶', name: 'speechless mute quiet blank', category: 'smileys' },
  { char: '😏', name: 'smirk cunning arrogant sly proud', category: 'smileys' },
  { char: '😒', name: 'unamused bored skeptical roll eyes', category: 'smileys' },
  { char: '🙄', name: 'rolling eyes whatever annoyed sarcastic', category: 'smileys' },
  { char: '😬', name: 'grimacing awkward yikes tense', category: 'smileys' },
  { char: '🤥', name: 'lying pinocchio long nose untruthful', category: 'smileys' },
  { char: '😌', name: 'relieved calm peaceful content', category: 'smileys' },
  { char: '😔', name: 'pensive sad depressed sorrow', category: 'smileys' },
  { char: '😪', name: 'sleepy snot tired sleepy', category: 'smileys' },
  { char: '🤤', name: 'drooling hungry desire craving', category: 'smileys' },
  { char: '😴', name: 'sleeping zzz tired bed', category: 'smileys' },
  { char: '😷', name: 'medical mask sick covid health', category: 'smileys' },
  { char: '🤒', name: 'thermometer fever ill sick', category: 'smileys' },
  { char: '🤕', name: 'head bandage hurt injured accident', category: 'smileys' },
  { char: '🤢', name: 'nauseated sick green disgusted gross', category: 'smileys' },
  { char: '🤮', name: 'vomiting puke sick barf disgusted', category: 'smileys' },
  { char: '🤧', name: 'sneezing tissue sick cold', category: 'smileys' },
  { char: '🥵', name: 'hot face sweating red heat summer', category: 'smileys' },
  { char: '🥶', name: 'cold face freezing blue ice winter', category: 'smileys' },
  { char: '🥴', name: 'woozy drunk tipsy dizzy dazed', category: 'smileys' },
  { char: '😵', name: 'dizzy knocked out crossed eyes dead', category: 'smileys' },
  { char: '🤯', name: 'exploding head mind blown shocked boom', category: 'smileys' },
  { char: '🤠', name: 'cowboy hat western sheriff partner', category: 'smileys' },
  { char: '🥳', name: 'partying celebrate birthday hat horn', category: 'smileys' },
  { char: '😎', name: 'sunglasses cool boss confident awesome', category: 'smileys' },
  { char: '🤓', name: 'nerd geek glasses smart clever', category: 'smileys' },
  { char: '🧐', name: 'monocle investigate formal classy inspect', category: 'smileys' },
  { char: '😕', name: 'confused puzzled hesitant unsure', category: 'smileys' },
  { char: '😟', name: 'worried nervous anxious concern', category: 'smileys' },
  { char: '🙁', name: 'frowning sad unhappy gloomy', category: 'smileys' },
  { char: '😮', name: 'open mouth wow surprise astonished', category: 'smileys' },
  { char: '😯', name: 'hushed quiet surprised whoa', category: 'smileys' },
  { char: '😲', name: 'astonished shocked amazed stunned', category: 'smileys' },
  { char: '😳', name: 'flushed blushed wide eyed red face', category: 'smileys' },
  { char: '🥺', name: 'pleading puppy eyes beg cute mercy', category: 'smileys' },
  { char: '😦', name: 'frowning open mouth aghast shock', category: 'smileys' },
  { char: '😧', name: 'anguished distressed alarmed troubled', category: 'smileys' },
  { char: '😨', name: 'fearful scared afraid panicked', category: 'smileys' },
  { char: '😰', name: 'anxious sweat blue worried dread', category: 'smileys' },
  { char: '😥', name: 'sad relieved disappointed whew', category: 'smileys' },
  { char: '😢', name: 'crying tear sad weeping grief', category: 'smileys' },
  { char: '😭', name: 'loudly crying sobbing bawling heartbroken', category: 'smileys' },
  { char: '😱', name: 'screaming fear horror scream munch home alone', category: 'smileys' },
  { char: '😖', name: 'confounded quivering frustrated struggle', category: 'smileys' },
  { char: '😣', name: 'persevering helpless suffering endure', category: 'smileys' },
  { char: '😞', name: 'disappointed downcast defeat regret', category: 'smileys' },
  { char: '😓', name: 'downcast sweat hard work exhausted', category: 'smileys' },
  { char: '😩', name: 'weary tired frustrated agonizing groan', category: 'smileys' },
  { char: '😫', name: 'tired fed up exasperated helpless', category: 'smileys' },
  { char: '🥱', name: 'yawning sleepy bored tired exhausted', category: 'smileys' },
  { char: '😤', name: 'triumph huffing steam angry proud arrogant', category: 'smileys' },
  { char: '😡', name: 'pouting rage angry red furious mad', category: 'smileys' },
  { char: '😠', name: 'angry annoyed irritated grumpy', category: 'smileys' },
  { char: '🤬', name: 'swearing cursing profanity angry symbols', category: 'smileys' },
  { char: '😈', name: 'devil horns mischievous smiling evil', category: 'smileys' },
  { char: '👿', name: 'angry devil horned wicked furious', category: 'smileys' },
  { char: '💀', name: 'skull skeleton dead dying death lol', category: 'smileys' },
  { char: '☠️', name: 'skull and crossbones pirate danger poison', category: 'smileys' },
  { char: '💩', name: 'poop pile dung crap funny', category: 'smileys' },
  { char: '🤡', name: 'clown circus funny silly foolish', category: 'smileys' },
  { char: '👻', name: 'ghost halloween spooky boo spirit', category: 'smileys' },
  { char: '👽', name: 'alien ufo extra terrestrial martian', category: 'smileys' },
  { char: '🤖', name: 'robot droid technology automation ai', category: 'smileys' },

  // --- Hands & Gestures ---
  { char: '👍', name: 'thumbs up like approve good yes ok agree', category: 'gestures' },
  { char: '👎', name: 'thumbs down dislike bad disapprove no hate', category: 'gestures' },
  { char: '👊', name: 'fist punch knuckle brofist bump hit', category: 'gestures' },
  { char: '✊', name: 'raised fist power solidarity strength resistance', category: 'gestures' },
  { char: '🤛', name: 'left fist bump greeting knuckles', category: 'gestures' },
  { char: '🤜', name: 'right fist bump greeting respect', category: 'gestures' },
  { char: '👏', name: 'clapping hands applause bravo congrats praise', category: 'gestures' },
  { char: '🙌', name: 'raising hands celebrate praise hooray worship', category: 'gestures' },
  { char: '👐', name: 'open hands hug welcome honesty jazz hands', category: 'gestures' },
  { char: '🤲', name: 'palms up together prayer offering gratitude', category: 'gestures' },
  { char: '🤝', name: 'handshake deal agreement partnership business partner', category: 'gestures' },
  { char: '🙏', name: 'folded hands pray please thank you namaste gratitude', category: 'gestures' },
  { char: '✍️', name: 'writing hand note signing pencil memo', category: 'gestures' },
  { char: '💅', name: 'nail polish sassy fabulous manicure glam', category: 'gestures' },
  { char: '🤳', name: 'selfie camera smartphone photo pose', category: 'gestures' },
  { char: '💪', name: 'flexed biceps muscle strong workout fitness power', category: 'gestures' },
  { char: '👈', name: 'backhand index pointing left direction', category: 'gestures' },
  { char: '👉', name: 'backhand index pointing right direction', category: 'gestures' },
  { char: '👆', name: 'backhand index pointing up above', category: 'gestures' },
  { char: '👇', name: 'backhand index pointing down below', category: 'gestures' },
  { char: '☝️', name: 'index pointing up attention one wait look', category: 'gestures' },
  { char: '✋', name: 'raised hand stop high five palm halt', category: 'gestures' },
  { char: '🤚', name: 'raised back of hand stop back', category: 'gestures' },
  { char: '🖐️', name: 'hand with fingers splayed five high five', category: 'gestures' },
  { char: '🖖', name: 'vulcan salute spock live long prosper star trek', category: 'gestures' },
  { char: '👋', name: 'waving hand hello goodbye hi bye greet', category: 'gestures' },
  { char: '🤙', name: 'call me shaka hang loose surf phone', category: 'gestures' },
  { char: '👌', name: 'ok hand perfect fine agreement nice', category: 'gestures' },
  { char: '🤌', name: 'pinched fingers italian chef kiss what do you mean', category: 'gestures' },
  { char: '🤏', name: 'pinching hand small little tiny bit', category: 'gestures' },
  { char: '✌️', name: 'victory hand peace two sign', category: 'gestures' },
  { char: '🤞', name: 'crossed fingers good luck hope wish', category: 'gestures' },
  { char: '🤟', name: 'love you gesture sign language rock', category: 'gestures' },
  { char: '🤘', name: 'sign of horns rock on metal concert', category: 'gestures' },
  { char: '👀', name: 'eyes look watching seeing inspect curious gaze', category: 'gestures' },
  { char: '👁️', name: 'eye look vision watch observe single', category: 'gestures' },
  { char: '🧠', name: 'brain smart intelligent neurology memory intellect', category: 'gestures' },

  // --- Hearts & Symbols ---
  { char: '❤️', name: 'red heart love romance affection favorite', category: 'symbols' },
  { char: '🧡', name: 'orange heart friendship warmth autumn', category: 'symbols' },
  { char: '💛', name: 'yellow heart positivity loyalty happiness', category: 'symbols' },
  { char: '💚', name: 'green heart nature eco envy health', category: 'symbols' },
  { char: '💙', name: 'blue heart trust peace loyalty cool', category: 'symbols' },
  { char: '💜', name: 'purple heart luxury royalty magic compassion', category: 'symbols' },
  { char: '🖤', name: 'black heart dark gothic sorrow dark humor', category: 'symbols' },
  { char: '🤍', name: 'white heart pure clean peaceful angel', category: 'symbols' },
  { char: '🤎', name: 'brown heart earth chocolate cozy', category: 'symbols' },
  { char: '💔', name: 'broken heart heartbreak sad sorrow breakup', category: 'symbols' },
  { char: '❣️', name: 'heart exclamation emphasis excited love', category: 'symbols' },
  { char: '💕', name: 'two hearts love floating affection', category: 'symbols' },
  { char: '💞', name: 'revolving hearts love connection orbiting', category: 'symbols' },
  { char: '💓', name: 'beating heart love pulse heartbeat alive', category: 'symbols' },
  { char: '💗', name: 'growing heart loving expanding excitement', category: 'symbols' },
  { char: '💖', name: 'sparkling heart shiny love glamour dazzling', category: 'symbols' },
  { char: '💘', name: 'heart with arrow cupid love romance match', category: 'symbols' },
  { char: '💝', name: 'heart with ribbon gift present valentine love', category: 'symbols' },
  { char: '🔥', name: 'fire hot lit trending flame passionate burn', category: 'symbols' },
  { char: '✨', name: 'sparkles clean magic shine special star new', category: 'symbols' },
  { char: '🌟', name: 'glowing star shine bright rated winner', category: 'symbols' },
  { char: '⭐', name: 'star favorite review bookmark rating rank', category: 'symbols' },
  { char: '⚡', name: 'high voltage lightning bolt zap fast instant electricity', category: 'symbols' },
  { char: '💥', name: 'collision boom impact explosion bang pop', category: 'symbols' },
  { char: '💯', name: 'hundred points percent perfect score a-plus real', category: 'symbols' },
  { char: '✅', name: 'check mark button verified done complete approved pass', category: 'symbols' },
  { char: '✔️', name: 'check mark tick done correct yes', category: 'symbols' },
  { char: '❌', name: 'cross mark cancel reject wrong error fail no', category: 'symbols' },
  { char: '⭕', name: 'heavy large circle ok correct valid red circle', category: 'symbols' },
  { char: '🛑', name: 'stop sign octagonal halt cease danger', category: 'symbols' },
  { char: '⚠️', name: 'warning alert caution danger problem caution', category: 'symbols' },
  { char: '🚫', name: 'prohibited forbidden denied banned entry no', category: 'symbols' },
  { char: '🔔', name: 'bell notification alert chime reminder alarm', category: 'symbols' },
  { char: '🔕', name: 'bell with slash muted silent quiet disturbance', category: 'symbols' },
  { char: '💡', name: 'light bulb idea inspiration smart innovation eureka', category: 'symbols' },
  { char: '🎯', name: 'bullseye target goal accurate aim objective score', category: 'symbols' },
  { char: '💬', name: 'speech balloon comment chat message reply talk', category: 'symbols' },
  { char: '💭', name: 'thought balloon dream thinking ponder bubble', category: 'symbols' },
  { char: '💤', name: 'zzz sleeping tired snooze dormant bedtime', category: 'symbols' },

  // --- Objects, Trade & Business ---
  { char: '🎉', name: 'party popper confetti celebrate congratulations milestone', category: 'objects' },
  { char: '🎊', name: 'confetti ball celebration festive event party', category: 'objects' },
  { char: '🎈', name: 'balloon birthday festival celebrate floating', category: 'objects' },
  { char: '🎁', name: 'wrapped gift present surprise bonus package', category: 'objects' },
  { char: '🏆', name: 'trophy champion winner award first place prize', category: 'objects' },
  { char: '🥇', name: '1st place medal gold champion winner best', category: 'objects' },
  { char: '🥈', name: '2nd place medal silver runner up', category: 'objects' },
  { char: '🥉', name: '3rd place medal bronze third winner', category: 'objects' },
  { char: '💎', name: 'gem stone diamond premium luxury valuable crystal', category: 'objects' },
  { char: '👑', name: 'crown royal king queen monarch leader royalty', category: 'objects' },
  { char: '🚀', name: 'rocket launch fast speed scale venture startup moon', category: 'objects' },
  { char: '📦', name: 'package parcel shipping delivery box wholesale logistics', category: 'objects' },
  { char: '🏷️', name: 'label tag price discount product badge', category: 'objects' },
  { char: '💰', name: 'money bag cash wealth financial rich payment', category: 'objects' },
  { char: '💵', name: 'dollar banknote cash currency payment transaction', category: 'objects' },
  { char: '💳', name: 'credit card payment purchase checkout stripe debit', category: 'objects' },
  { char: '🧾', name: 'receipt invoice document bill purchase order proof', category: 'objects' },
  { char: '🛒', name: 'shopping cart buy store checkout ecommerce retail', category: 'objects' },
  { char: '💼', name: 'briefcase business professional work job executive', category: 'objects' },
  { char: '📅', name: 'calendar date schedule appointment timeline deadline', category: 'objects' },
  { char: '📈', name: 'chart increasing upward trend growth profit stock rise', category: 'objects' },
  { char: '📉', name: 'chart decreasing downward trend drop loss reduction', category: 'objects' },
  { char: '📊', name: 'bar chart analytics metrics data statistics report', category: 'objects' },
  { char: '📌', name: 'pushpin pin priority notice board mark location', category: 'objects' },
  { char: '📍', name: 'round pushpin map location destination tracking warehouse', category: 'objects' },
  { char: '📎', name: 'paperclip attachment document link join staple', category: 'objects' },
  { char: '🔒', name: 'locked security privacy protected safe escrow key', category: 'objects' },
  { char: '🔓', name: 'unlocked open access released accessible free', category: 'objects' },
  { char: '🔑', name: 'key access unlock password auth security token', category: 'objects' },
  { char: '🔨', name: 'hammer tool build construction maintenance repair', category: 'objects' },
  { char: '🔧', name: 'wrench mechanic setting tool adjust options repair', category: 'objects' },
  { char: '⚙️', name: 'gear cog setting system configure preferences', category: 'objects' },
  { char: '📱', name: 'mobile phone smartphone screen cellular call contact', category: 'objects' },
  { char: '💻', name: 'laptop computer pc tech screen software developer', category: 'objects' },
  { char: '🚚', name: 'delivery truck freight transport courier shipping logistics', category: 'objects' },
  { char: '✈️', name: 'airplane air freight express flight travel overseas export', category: 'objects' },
  { char: '🚢', name: 'ship sea cargo ocean freight container maritime vessel', category: 'objects' },

  // --- Nature & Food ---
  { char: '☕', name: 'coffee tea hot drink beverage cafe morning energy', category: 'nature' },
  { char: '🍕', name: 'pizza slice food cheese fast food restaurant Italian', category: 'nature' },
  { char: '🍔', name: 'hamburger burger fast food diner beef lunch', category: 'nature' },
  { char: '🍟', name: 'french fries potato snack side fast food', category: 'nature' },
  { char: '🍻', name: 'clinking beer mugs cheers celebration toast bar drinks', category: 'nature' },
  { char: '🥂', name: 'clinking glasses champagne toast celebrate wedding congrats', category: 'nature' },
  { char: '🍷', name: 'wine glass red alcoholic drink beverage dinner', category: 'nature' },
  { char: '🍩', name: 'doughnut donut sweet dessert pastry sugar glazed', category: 'nature' },
  { char: '🍪', name: 'cookie biscuit chocolate chip dessert sweet snack', category: 'nature' },
  { char: '🎂', name: 'birthday cake anniversary party celebration dessert', category: 'nature' },
  { char: '🍎', name: 'red apple fruit health natural healthy teacher', category: 'nature' },
  { char: '🥑', name: 'avocado fruit food guacamole green toast', category: 'nature' },
  { char: '🌮', name: 'taco mexican food wrap snack dinner', category: 'nature' },
  { char: '🍣', name: 'sushi japanese food raw fish rice dinner delicacy', category: 'nature' },
  { char: '🍜', name: 'steaming bowl ramen noodles soup hot asian', category: 'nature' },
  { char: '☀️', name: 'sun sunny bright weather summer day shine gold', category: 'nature' },
  { char: '🌙', name: 'crescent moon night evening sky dark bedtime', category: 'nature' },
  { char: '🌈', name: 'rainbow colorful weather hope pride bright sky', category: 'nature' },
  { char: '❄️', name: 'snowflake cold winter ice frost chilly freeze', category: 'nature' },
  { char: '🌊', name: 'water wave ocean sea surf tsunami beach tide', category: 'nature' },
  { char: '🍀', name: 'four leaf clover luck lucky Irish green st patricks', category: 'nature' },
  { char: '🌸', name: 'cherry blossom flower pink floral spring bloom', category: 'nature' },
  { char: '🌺', name: 'hibiscus flower tropical hawaii floral bloom red', category: 'nature' },
  { char: '🌻', name: 'sunflower yellow floral summer seed bright happy', category: 'nature' },
  { char: '🌱', name: 'seedling sprout plant grow nature beginning green', category: 'nature' },
  { char: '🌍', name: 'globe showing europe africa world earth international planet', category: 'nature' },
];
